### ISSUE TITLE
No JS found, can't show configuration and other items

### ISSUE THREAD

**Issue by wbste** [Martijn02/pebble-solaredge-status#1]
When I forked the project, I get "No JS found, can't show configuration" in CloudPebble, and no cards/windows load on the emulator. Any ideas on what's going on? That appears in the console when I try to launch the config page. If you could help me figure that out, I'd like to modify some of your code, if you don't mind :) Some examples of what I'd like to do are below:

---

On your config webpage: http://martijn.vanzal.com/sestatus/

```
    <div data-role="fieldcontain">
      <label for="name">Max power (KWh):</label>
      <input type="text" name="maxPower" id="maxPower"></textarea>
    </div>
```

Does max power mean the Solar Array max output? If so, that would be kWp (for kiloWatts peak), not kWh.

Now looking at app.js,
    function(data) {
      var today = data.overview.lastDayData.energy / 1000;
      var month = data.overview.lastMonthData.energy / 1000;
      var total = data.overview.lifeTimeData.energy / 1000;
      card.subtitle(today.toFixed(2) + 'kWh');
      card.body('Today: ' + today.toFixed(2) + 'kWh\n' +
                'Month: ' + month.toFixed(2) + 'kWh\n' +
                'Total: ' + total.toFixed(2) + 'kWh\n' + 
                'Power ' + data.overview.currentPower.power + 'W\n');

Could you make the units variable, like so:
      // Month Energy
      var month = data.overview.lastMonthData.energy; //Wh
      var monthunits = "Wh";
      if (month > 1000 && month <1000000) {
        month = month / 1000;
        var monthunits = "kWh";
      }        
      if (month > 1000000) {
        month = month / 1000000;
        var monthunits = "MWh";
      }

**Comment by Martijn02** [comment]
Hi, Thank you for your comments.

I'm not sure why the configuration doesn't work correctly on cloudpebble, it works correctly if you build and run to your pebble. (Developer mode)

The max power is optional (I should make that more clear) and it is used for the detail graphs. If you set a max, and push up or down on the details page to go to the prev/next day, all the graphs will use the same scale. If you don't set it up, the graph drawing function will automatically fit the graph to the available space. (That means a 1000W peak on a rainy day will be the same height as a 3000W peak on a sunny day)

Oh, and the value should be entered in watts (not Kilowatts) My SE3000 can theoretically produce up to 3200W, but it rarely goes over 3000W, so I set it to 3000.

I was already eyeing that piece of code from your solar monitor project, if you don't mind me stealing it, I will definitely make the units more flexible.

If you have any other ideas or requests, feel free to create (separate) tickets for them. Merge requests are also welcome.

**Comment by wbste** [comment]
Excellent, thanks for the reply.
Feel free to take any of my code: https://github.com/ace7196/SolarMonitor

I'm just getting my feet wet with Pebble.js, and I thought this was a cool project. Since I didn't see anything on the Pebble Store, I submitted my program, only to find you submit yours the same day :)

Great minds...
